name = "RTableTools"
uuid = "76227a05-389e-44bd-84ad-996dde4b1834"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TidierData = "fe2206b3-d496-4ee9-a338-6a095c4ece80"

[compat]
CSV = "0.10"
DataFrames = "1.5, 1.6"
DocStringExtensions = "0.9"
PrecompileTools = "1.1"
RDatasets = "0.7"
Reexport = "1.2"
TidierData = "0.11, 0.12, 1"
julia = "1.8, 1.9"

[extras]
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "RDatasets"]
